### ISSUE TITLE
Version installed with Pip is 1.0.6

### ISSUE THREAD

**Issue by felixveysseyre** [spacetelescope/spherical_geometry#109] opened 2017-07-19 11:55 UTC
Hello,

When installing `spherical_geometry` library with `pip`, the version installed is 1.0.6.

Could you update the package to the latest stable version ?

Thanks

**Comment by pllim** [comment] 2017-07-19 13:59
This is a duplicate of #102, so closing . For now, if you use Anaconda, you can grab the latest release from our "astroconda" channel.

**Closed by pllim** 2017-07-19 13:59 UTC
